# run: conda env create -f conda.cellprofiler.nopip.novers.yml
# run: conda env remove -n cellprofiler2
name: cellprofiler3
channels:
  - anaconda
  - goodman
  - bioconda
  - cyclus
  - conda-forge
dependencies:
  - appdirs
  - boto3
  - cython
  - h5py
  - ipywidgets
  - java-jdk
  - joblib
  - jupyter
  - libtiff
  - libxml2
  - libxslt
  - lxml
  - packaging
  - pillow
  - pip
  - python==3.6.3
  - pyzmq
  - mahotas
  - matplotlib
  - mysqlclient
  - numpy
  - raven
  - requests
  - scikit-image
  - scikit-learn
  - scipy
  - sphinx
  - tifffile
#  - wxpython==3.0.2.0
#  - pip:
#    - cellh5
#    - centrosome # installed prior
#    - inflect
#    - prokaryote==2.4.1 # version requirement: 10/1/19
#    - javabridge==1.0.15 # version requirement: 10/1/19
#    - python-bioformats==1.5.2
#    - git+https://github.com/CellProfiler/CellProfiler.git@v3.1.8
